-- Produtos cadastrados
create table produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  tipo text not null check (tipo in ('Produzido', 'Insumo')),
  unidade_medida text not null check (unidade_medida in ('Unidade', 'Gramas', 'Fatias')),
  validade_dias int not null,
  congelado boolean not null default false,
  fatias_porcoes int not null default 1,
  ativo boolean not null default true,
  created_at timestamptz default now()
);

-- Ordens de produção (loja → cozinha)
create table ordens_producao (
  id uuid primary key default gen_random_uuid(),
  produto_id uuid references produtos(id),
  quantidade int not null,
  loja_destino text not null check (loja_destino in ('loja1', 'loja2', 'cozinha')),
  status text not null default 'pendente' check (status in ('pendente', 'em_producao', 'concluida', 'cancelada')),
  solicitado_por text not null,
  observacao text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Lotes produzidos pela cozinha
create table lotes_producao (
  id uuid primary key default gen_random_uuid(),
  codigo_qr text unique not null,
  produto_id uuid references produtos(id),
  ordem_id uuid references ordens_producao(id),
  quantidade int not null,
  peso_gramas numeric,
  data_producao date not null default current_date,
  data_validade date not null,
  produzido_por text not null,
  destino text not null check (destino in ('cozinha', 'loja1', 'loja2')),
  status text not null default 'na_cozinha' check (status in ('na_cozinha', 'enviado', 'na_loja', 'esgotado')),
  created_at timestamptz default now()
);

-- Movimentações de estoque
create table movimentacoes_estoque (
  id uuid primary key default gen_random_uuid(),
  lote_id uuid references lotes_producao(id),
  tipo text not null check (tipo in ('entrada', 'saida', 'transferencia')),
  local_origem text check (local_origem in ('cozinha', 'loja1', 'loja2')),
  local_destino text check (local_destino in ('cozinha', 'loja1', 'loja2')),
  quantidade int not null,
  registrado_por text not null,
  created_at timestamptz default now()
);

-- Seed: produtos da AlgoDoce
insert into produtos (nome, tipo, unidade_medida, validade_dias, congelado, fatias_porcoes) values
('Bentô Cake G', 'Produzido', 'Unidade', 5, false, 1),
('Bentô Cake M', 'Produzido', 'Unidade', 5, false, 1),
('Bentô Cake P', 'Produzido', 'Unidade', 5, false, 1),
('Massa Vulcão de Chocolate', 'Insumo', 'Unidade', 15, false, 1),
('Massa Caseirinho Chocolate', 'Insumo', 'Unidade', 15, false, 1),
('Massa Caseirinho Branca', 'Insumo', 'Unidade', 15, false, 1),
('Massa Vulcão de Cenoura', 'Insumo', 'Unidade', 90, true, 1),
('Massa Vulcão de Baunilha', 'Insumo', 'Unidade', 90, true, 1),
('Brownie 25x35', 'Insumo', 'Unidade', 10, false, 1),
('Recheio Brigadeiro Trufado', 'Insumo', 'Gramas', 10, false, 3600),
('Recheio Ninho Trufado', 'Insumo', 'Gramas', 10, false, 3600),
('Massa Fondue', 'Insumo', 'Unidade', 90, true, 1),
('Brigadeiro para Enrolar Choc. Preto', 'Insumo', 'Gramas', 10, false, 500),
('Brigadeiro para Enrolar Leite Ninho', 'Insumo', 'Gramas', 10, false, 500),
('Copo Supreme Ninho c/ Nutella', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Brigadeiro', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Choconinho', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Ferrero', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Ninho', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Ninho com Morango', 'Produzido', 'Unidade', 10, false, 1),
('Copo Supreme Sensação', 'Produzido', 'Unidade', 10, false, 1),
('Coxinha de Morango', 'Produzido', 'Unidade', 3, false, 1),
('Croissant', 'Produzido', 'Unidade', 90, true, 1),
('Bolo em Fatia Amoré', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Brigadeiro Trufado', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Choconinho', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Crocante de Nozes', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia de Abacaxi', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia de Prestígio', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Dois Amores', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Ferrero', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Flocos', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Franuí', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Kinder Branco', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Matilda', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Morangoffe', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Ninho c/ Frutas Vermelhas', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Ninho com Morango', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Pudim', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Red Velvet', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Sensação', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia Trufado de Maracujá', 'Produzido', 'Fatias', 7, false, 13),
('Bolo em Fatia WonderCake', 'Produzido', 'Fatias', 7, false, 13),
('Focaccia Alecrim (150g)', 'Produzido', 'Unidade', 5, false, 1),
('Mini Tortinha Brownininho', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Cheesecake', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Chocobrownie', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Chocolatudo', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Limonada Suíça', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Moça Bonita', 'Produzido', 'Unidade', 90, true, 1),
('Mini Tortinha Ninho Trufado', 'Produzido', 'Unidade', 90, true, 1),
('Pão Brioche (90g)', 'Produzido', 'Unidade', 90, true, 1),
('Pão de Beterraba', 'Produzido', 'Unidade', 90, true, 1),
('Pão de Ervas', 'Produzido', 'Unidade', 90, true, 1),
('Pão de Queijo & Bacon', 'Produzido', 'Unidade', 90, true, 1),
('Torta Algodoce', 'Produzido', 'Fatias', 7, false, 8),
('Torta Amor Perfeito', 'Produzido', 'Fatias', 7, false, 8),
('Torta Bombom', 'Produzido', 'Fatias', 7, false, 8),
('Torta Bombom de Morango', 'Produzido', 'Fatias', 7, false, 8),
('Torta Cheesecake', 'Produzido', 'Fatias', 7, false, 8),
('Torta Choconozes', 'Produzido', 'Fatias', 7, false, 8),
('Torta de Limão', 'Produzido', 'Fatias', 7, false, 8),
('Torta de Limão Trufada', 'Produzido', 'Fatias', 7, false, 8),
('Torta Ferrero', 'Produzido', 'Fatias', 7, false, 8),
('Torta Limonada Suíça', 'Produzido', 'Fatias', 7, false, 8),
('Torta Moça Bonita', 'Produzido', 'Fatias', 7, false, 8),
('Torta Morangoffe', 'Produzido', 'Fatias', 7, false, 8),
('Torta Ninho Trufado', 'Produzido', 'Fatias', 7, false, 8),
('Torta Paixão', 'Produzido', 'Fatias', 7, false, 8),
('Torta Palha Italiana', 'Produzido', 'Fatias', 7, false, 8),
('Torta Pedaço do Céu', 'Produzido', 'Fatias', 7, false, 8),
('Torta Supreme de Uva', 'Produzido', 'Fatias', 7, false, 8),
('Coulis de Frutas Vermelhas', 'Insumo', 'Gramas', 90, true, 500),
('Coulis de Maracujá', 'Insumo', 'Gramas', 90, true, 200),
('Caramelo Toffee', 'Insumo', 'Gramas', 90, true, 500);
